/**
 * auto-documenter
 * Generates an overview of all skills.
 */

const fs = require('fs');
const path = require('path');

function getSkillInfo(skillDir) {
  const skillMdPath = path.join(skillDir, 'SKILL.md');
  if (!fs.existsSync(skillMdPath)) return null;

  const content = fs.readFileSync(skillMdPath, 'utf8');
  const frontmatterMatch = content.match(/---([\s\S]*?)---/);
  
  if (frontmatterMatch) {
    const yaml = frontmatterMatch[1];
    const nameMatch = yaml.match(/name:\s*(.*)/);
    const descMatch = yaml.match(/description:\s*(.*)/);
    
    return {
      name: nameMatch ? nameMatch[1].trim() : path.basename(skillDir),
      description: descMatch ? descMatch[1].trim() : 'No description provided.'
    };
  }
  return {
    name: path.basename(skillDir),
    description: 'No frontmatter found.'
  };
}

function updateOverview() {
  const skillsBase = path.join(process.cwd(), 'skills');
  const skills = fs.readdirSync(skillsBase).filter(f => {
    return fs.statSync(path.join(skillsBase, f)).isDirectory();
  });

  let md = "# Skills Overview\n\nThis file is automatically generated by the `auto-documenter` skill.\n\n";
  md += "| Skill Name | Description |\n";
  md += "| :--- | :--- |\n";

  const infos = skills.map(s => getSkillInfo(path.join(skillsBase, s))).filter(Boolean);
  
  infos.sort((a, b) => a.name.localeCompare(b.name)).forEach(info => {
    md += `| **${info.name}** | ${info.description} |\n`;
  });

  const outputPath = path.join(process.cwd(), 'SKILLS_OVERVIEW.md');
  fs.writeFileSync(outputPath, md);
  return outputPath;
}

module.exports = {
  updateOverview,
  main: () => {
    console.log('Updating skills overview...');
    const path = updateOverview();
    console.log(`Overview updated at: ${path}`);
    return path;
  }
};
